server:
  port: 20071

spring:
  application:
    name: com.payconiq.stocks
  datasource:
    url: jdbc:h2:./stocks;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true